name: 'Setup YQ'
description: 'Install YQ and add it to the PATH'
author: 'ibiqlik'

inputs:
  yq_version:
    description: 'The YQ version to install'
    required: false
    default: '3.3.2'

runs:
  using: 'node12'
  main: 'main.js'
