name: Print event info
description: 'Prints event info'
runs:
  using: "composite"
  steps:
    - id: print-event-info
      run: |
        echo GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
        echo GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}
        cat ${GITHUB_EVENT_PATH}
      shell: bash
