name: 'Slack Notification'
description: 'Send Slack notification about dev cluster creation'
inputs:
  repository:
    description: 'The team repository'
    required: true
  webhook:
    description: 'Slack webhook'
    required: true
  channel:
    description: 'Slack channel (or user) to notify (defaults to botSlackChannel in components.yaml)'
    required: false
  message:
    description: 'Message to post on Slack'
    required: true

runs:
  using: 'composite'
  steps:
  - id: post_slack_notification
    run: ${{ github.action_path }}/main.sh
    shell: bash
    env:
      INPUT_SLACK_WEBHOOK: ${{ inputs.webhook }}
      INPUT_REPOSITORY: ${{ inputs.repository }}
      INPUT_CHANNEL: ${{ inputs.channel }}
      INPUT_MESSAGE: ${{ inputs.message }}