name: 'Setup Gomplate'
description: 'Install Gomplate and add it to the PATH'
author: 'ibiqlik'

inputs:
  gomplate_version:
    description: 'Gomplate version'
    required: false
    default: '3.8.0'

runs:
  using: 'composite'
  steps:
    - id: setup_gomplate
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_GOMPLATE_VERSION: ${{ inputs.gomplate_version }}
