name: 'SemVer - Generate version based on tag, commit id'
description: 'Generate a version based on latest release tag (v*.*.*) and short commit id or just return pushed tag (*.*.*)'
author: 'ibiqlik'

outputs:
  version:
    description: 'Returns SemVer format *.*.* or *.*.*-shortCommitID'
  commit_sha:
    description: 'Returns commit sha ID'
  branch_name:
    description: 'Returns Branch Name'
  release_tag:
    description: 'Returns [1|0]; If semver vX.Y.Z is pushed RELEASE_TAG is set to 1'

runs:
  using: 'node12'
  main: 'main.js'
