name: Verify compliance
description: 'Performs a specific type of verification'
outputs:
  verification-status:
    description: "Verification status"
    value: ${{ steps.run-verification-command.outputs.verification-status }}
runs:
  using: "composite"
  steps:
    - id: clone-repo-with-verification-commands
      run: |
        export BRANCH_ARG=$(if [ -z ${VERIFICATION_COMMAND_REPO_BRANCH} ]; then echo ""; else echo "-b ${VERIFICATION_COMMAND_REPO_BRANCH}"; fi)
        echo ${GITHUB_TOKEN} | xargs -I % git clone ${BRANCH_ARG} https://%@github.com/${VERIFICATION_COMMAND_REPO}.git
      shell: bash
    - id: run-verification-command
      run: |
        export VERIFICATION_COMMAND_REPO_NAME=${VERIFICATION_COMMAND_REPO#*/}
        export VERIFICATION_TYPE_WITH_UNDERSCORES=$(echo ${VERIFICATION_TYPE} | tr '-' '_')
        cd ${VERIFICATION_COMMAND_REPO_NAME}/cmd/verify_${VERIFICATION_TYPE_WITH_UNDERSCORES}
        go run main.go ${TARGET_NAME} ${TARGET_REF}
        export VERIFICATION_STATUS=$(cat ${VERIFICATION_TYPE}-status.txt)
        echo ${VERIFICATION_TYPE} status: ${VERIFICATION_STATUS}
        echo "::set-output name=verification-status::$(echo $VERIFICATION_STATUS)"
        if [ "${VERIFICATION_STATUS}" = "failure" ] || [ "${VERIFICATION_STATUS}" = "error" ]; then exit 1; fi
      shell: bash
