name: 'Make GitHub workflow dispatch call'
description: 'Used to trigger a workflow processes'
author: 'ibiqlik'

inputs:
  owner:
    required: true
    description: 'GitHub owner'
  repository:
    required: true
    description: 'GitHub repository'
  ref:
    required: false
    description: 'Target ref, can be branch or tag. Defaults to repository default branch'
  workflow:
    required: true
    description: 'GitHub workflow on target repository'
  inputs:
    required: true
    description: '{"input1":"value2","input2":"value2"}'

runs:
  using: 'composite'
  steps:
    - id: workflow-dispatch
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_WORKFLOW: ${{ inputs.workflow }}
        INPUT_INPUTS: ${{ inputs.inputs }}
