name: 'Make GitHub repository dispatch call'
description: 'Used to trigger a webhook repository_dispatch event'
author: 'ibiqlik'

inputs:
  owner:
    required: true
    description: 'GitHub owner'
  repository:
    required: true
    description: 'GitHub repository'
  event_type:
    required: true
    description: 'Event type'
  client_payload:
    required: false
    description: '{"input1":"value1","input2":"value2"}'

runs:
  using: 'composite'
  steps:
    - id: workflow-dispatch
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_EVENT_TYPE: ${{ inputs.event_type }}
        INPUT_CLIENT_PAYLOAD: ${{ inputs.client_payload }}
