name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3

    - name: shellcheck
      uses: ibiqlik/action-shellcheck@master
      with:
        severity: error
