name: Test
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: ./action-slack-notification
      with:
        repository: ci-tools
        message: "Hello World!"

